// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsQQsWLmBluKw41dvWLHyxNwSPVSKiPFs',
    appId: '1:434382061080:web:978c5bde98f8872adb8d6d',
    messagingSenderId: '434382061080',
    projectId: 'money-easy-mobile',
    authDomain: 'money-easy-mobile.firebaseapp.com',
    storageBucket: 'money-easy-mobile.firebasestorage.app',
    measurementId: 'G-GWNGCP3HMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg9Sv7X1XSQse332m6Ar1oIgwybXiMLvA',
    appId: '1:434382061080:android:952dbf0030701ad9db8d6d',
    messagingSenderId: '434382061080',
    projectId: 'money-easy-mobile',
    storageBucket: 'money-easy-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0cvHLa3k-vtJFKGQNyOHagrSMipCbujw',
    appId: '1:434382061080:ios:c9367213e6aaee91db8d6d',
    messagingSenderId: '434382061080',
    projectId: 'money-easy-mobile',
    storageBucket: 'money-easy-mobile.firebasestorage.app',
    iosBundleId: 'com.flutterflow.mesy',
  );
}
